### ISSUE TITLE
Request: tree-sitter-sqlite

### ISSUE THREAD

**Issue by simonw** [grantjenks/py-tree-sitter-languages#18]
From https://github.com/dhcmrlchtdj/tree-sitter-sqlite

**Comment by simonw** [comment]
I made some initial notes on `tree-sitter-sqlite` here: https://til.simonwillison.net/python/tree-sitter

**Comment by grantjenks** [comment]
Published in v1.7.0 with language name "sqlite"

**Comment by grantjenks** [comment]
Btw, thanks @simonw for all the posts. I've appreciated some of the recent ones about LLMs especially.
