### ISSUE TITLE
No matching distribution found

### ISSUE THREAD

**Issue by darrenburns** [grantjenks/py-tree-sitter-languages#20]
Hi, thanks for providing this. It seems very useful. We're trying to use it in the upcoming Textual TextArea widget.

Unfortunately, I'm having issues installing on an M1 Macbook Pro.

`poetry add tree_sitter_languages` returns with:
```
Unable to find installation candidates for tree-sitter-languages (1.7.0)
```

`pip install tree_sitter_languages` returns with:
```
ERROR: Could not find a version that satisfies the requirement tree_sitter_languages (from versions: none)
ERROR: No matching distribution found for tree_sitter_languages
```

Any insight or ideas on resolving this would be appreciated!

**Comment by grantjenks** [comment]
Does poetry insist on installing source distributions? Only binary wheels are published.
