### ISSUE TITLE
manylinux aarch64 release

### ISSUE THREAD

**Issue by Wisteria30** [grantjenks/py-tree-sitter-languages#26]
Could you release a manylinux package for the aarch64 architecture?
I tried to use it from the Docker environment on my M1 Mac, but the installation failed because I could not find the relevant package in PyPi.

**Comment by grantjenks** [comment]
Probably. PR welcome based on  https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation for Linux.

**Comment by grantjenks** [comment]
Also https://cibuildwheel.readthedocs.io/en/stable/faq/#universal2 and https://cibuildwheel.readthedocs.io/en/stable/faq/#windows-arm64

**Comment by grantjenks** [comment]
Should be released in 1.8.* as part of https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/6519541679
