### ISSUE TITLE
Duplicate tree-sitter-toml

### ISSUE THREAD

**Issue by Akuli** [grantjenks/py-tree-sitter-languages#3]
```
$ grep toml build.sh
git clone --depth 1 https://github.com/ikatyang/tree-sitter-toml
git clone --depth 1 https://github.com/tree-sitter/tree-sitter-toml
```

The first `git clone` succeeds, the second fails. Which tree-sitter-toml repository should we use? Perhaps `tree-sitter/tree-sitter-toml` as the name seems more official?

**Comment by grantjenks** [comment]
That latter is forked from the former and a couple commits ahead. Seems better to use the one in the tree-sitter org.
