### ISSUE TITLE
Wheels for Python 3.12

### ISSUE THREAD

**Issue by davidbrochart** [grantjenks/py-tree-sitter-languages#30]
Would it be possible to publish wheels for Python 3.12?

**Comment by GabDug** [comment]
#28 would allow this, need an update from py-tree-sitter https://github.com/tree-sitter/py-tree-sitter/pull/161

**Comment by paul-gauthier** [comment]
It looks like https://github.com/tree-sitter/py-tree-sitter/pull/161 has been merged. Any chance we could get an update of [py-tree-sitter-languages](https://github.com/grantjenks/py-tree-sitter-languages) to unlock python 3.12 support?

**Comment by Freed-Wu** [comment]
At least provide a sdist in PYPI to allow user to build python 3.12 wheel :cry:

**Comment by grantjenks** [comment]
Release builds running in https://github.com/grantjenks/py-tree-sitter-languages/pull/37 now

**Comment by grantjenks** [comment]
PR tests passed. Pushed a new tag which should release at https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7400244466

**Comment by ulgens** [comment]
It seems a new set of wheels are required for 3.13 . There is already [an open issue](https://github.com/grantjenks/py-tree-sitter-languages/issues/75) about it, even though it lacks details, but I wanted to ping people here too hoping it could speed up the process 🌷
