### ISSUE TITLE
What is the cause of this error： Could not find module 'C:\ProgramData\anaconda3\Lib\site-packages\tree_sitter_languages\languages.dll' 

### ISSUE THREAD

**Issue by ydteng** [grantjenks/py-tree-sitter-languages#31]
The full error message：
**FileNotFoundError: Could not find module 'C:\ProgramData\anaconda3\Lib\site-packages\tree_sitter_languages\languages.dll' (or one of its dependencies). Try using the full path with constructor syntax.**
How to fix it?

**Comment by grantjenks** [comment]
🤷‍♂️. Is the file not there? Is it not present in the wheel that was downloaded? Check those things first.

**Comment by ydteng** [comment]
> 🤷‍♂️. Is the file not there? Is it not present in the wheel that was downloaded? Check those things first.

Hello, author! I'm new to python and I don't quite understand what py-tree-sitter-languages actually do. When I first started using py-tree-sitter, I was prompted to install the Microsoft Visual c++ compiler, which I didn't want to install. So I found your warehouse. I don't think I need to download the C++ compiler anymore after I use py-tree-sitter-languages. But the error "FileNotFoundError: Could not find module 'C:\ProgramData\anaconda3\Lib\site-packages\tree_sitter_languages\languages.dll' ". I would like to know whether the installation will include the language.dll file? I am using conda installer, is this related to this error?

**Comment by grantjenks** [comment]
> I would like to know whether the installation will include the language.dll file?

It should. That’s the point of this project: to distribute pre-compiled binaries.

> I am using conda installer, is this related to this error?

I don’t know.

**Comment by ydteng** [comment]
I fixed that and it worked using pip！Thanks😊
