### ISSUE TITLE
Provide optional components

### ISSUE THREAD

**Issue by rlippmann** [grantjenks/py-tree-sitter-languages#34]
Very convenient package!

More of an enhancement request:

It would be nice to be able to be able to download just the binaries required through the optional components part of pip.

i.e. pip install tree-sitter-languages[python]
pip install tree-sitter-languages[python, javascript, java]

or even
pip install tree-sitter-languages[languages, text_file_formats]

**Comment by grantjenks** [comment]
I'm open to that but it seems like it would get pretty complicated.

If you want to test it out then I'm open to a PR.
