### ISSUE TITLE
New release 2.0.0

### ISSUE THREAD

**Issue by tancnle** [grantjenks/py-tree-sitter-languages#46]
@grantjenks Would it be possible to push a new release of `tree_sitter_languages`?

Many thanks for your work on this project.

**Comment by grantjenks** [comment]
Release triggered at https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7706777756

**Comment by tancnle** [comment]
Thank you for pushing a new release @grantjenks 🙇🏼 

I have noticed that macOS and windows wheels are not available on [PyPi](https://pypi.org/project/tree-sitter-languages/#files). I can see the macOS [build](https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7706777756/job/21002863775#step:6:3422) was completed successfully but the subsequent upload [job](https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7706777756/job/21009851542#step:6:1) did not include them 🤔

**Comment by tancnle** [comment]
Another data points, the links for the uploaded macOS and windows are both returning 404

- macOS: https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7706777756/job/21002863775#step:7:36
- windows: https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7706777756/job/21002863934#step:7:35

**Comment by tancnle** [comment]
I think both macOS and windows artefacts are overwritten by ubuntu ones because of this change https://github.com/grantjenks/py-tree-sitter-languages/pull/42/commits/bc2ba52151b99ddafd81ddfee14373d2844f6ec9.

**Comment by tancnle** [comment]
I think reverting back to `upload-artifact@v2` would be a quickest fix (https://github.com/grantjenks/py-tree-sitter-languages/pull/47)

**Comment by grantjenks** [comment]
Try 2 https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7720774276

**Comment by tancnle** [comment]
@grantjenks It seems that the build is failing https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7720774276/job/21051244235#step:4:10 due to artefacts not being found. I think it is due to some compatibility issue between `upload-artifact@v2` and `download-artifact@v4` 🤔 

I have reinstated `upload-artifact@v4` and ensure there are no naming conflicts ([ref](https://github.com/actions/upload-artifact/issues/478#issuecomment-1918746908)). The artefact links are shown up in the log.

<img width="989" alt="Screenshot 2024-01-31 at 10 59 20 pm" src="https://github.com/grantjenks/py-tree-sitter-languages/assets/756722/f3961a24-40c1-4e37-91f8-ffde99f78371">

Could you kindly have another look? 🙏🏼

**Comment by andreportela** [comment]
How can I test it on macOS M1?

**Comment by tancnle** [comment]
@andreportela We need to push a new release so the package with MacOS wheels will be available via PyPi. At the moment, you can download the wheels directly from the artefacts [page](https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7724884957/artifacts/1208494048).

1. Download `wheelhouse-macos-latest` and unpack the locally.
2. Select the appropriate one for your Python version and arch. For example, I use Python 3.11 on M1 so I select `tree_sitter_languages-1.10.1-cp311-cp311-macosx_11_0_arm64.whl`.

    ```shell
    ./
    tree_sitter_languages-1.10.1-cp310-cp310-macosx_10_9_x86_64.whl
    tree_sitter_languages-1.10.1-cp310-cp310-macosx_11_0_arm64.whl
    tree_sitter_languages-1.10.1-cp311-cp311-macosx_10_9_x86_64.whl
    tree_sitter_languages-1.10.1-cp311-cp311-macosx_11_0_arm64.whl
    tree_sitter_languages-1.10.1-cp312-cp312-macosx_10_9_x86_64.whl
    tree_sitter_languages-1.10.1-cp312-cp312-macosx_11_0_arm64.whl
    tree_sitter_languages-1.10.1-cp37-cp37m-macosx_10_9_x86_64.whl
    tree_sitter_languages-1.10.1-cp38-cp38-macosx_10_9_x86_64.whl
    tree_sitter_languages-1.10.1-cp38-cp38-macosx_11_0_arm64.whl
    tree_sitter_languages-1.10.1-cp39-cp39-macosx_10_9_x86_64.whl
    tree_sitter_languages-1.10.1-cp39-cp39-macosx_11_0_arm64.whl
    ```

3. Install the package
    ```shell
    ❯ pip install tree_sitter_languages-1.10.1-cp311-cp311-macosx_11_0_arm64.whl 
    ```

4. Try it out
     ```shell
     $ python
     Python 3.11.7 (main, Jan 15 2024, 18:10:15) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
     >>> from tree_sitter_languages import get_language, get_parser
     >>> language = get_language('python')
    >>>> parser = get_parser('python')
   ````

**Comment by tancnle** [comment]
👋🏼 @grantjenks would it be possible if you could please push another release or perhaps rebuild/push `1.10.1` 🙏🏼?

**Comment by grantjenks** [comment]
Try 2: https://github.com/grantjenks/py-tree-sitter-languages/actions/runs/7772134775
