### ISSUE TITLE
Error while using get_language() and get_parser()

### ISSUE THREAD

**Issue by MalikTalha03** [grantjenks/py-tree-sitter-languages#77]
python_language = get_language(lang)
                      ^^^^^^^^^^^^^^^^^^
  File "tree_sitter_languages/core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

**Comment by BlastWind** [comment]
Just had this error myself. Gotta use an earlier tree-sitter version:`pip install tree-sitter==0.21.3`.

The `tree-sitter` python binding had an breaking change in how the `Language` is set up in version `0.22`, see its [changelog](https://github.com/tree-sitter/py-tree-sitter/releases/tag/v0.22.0).

I suppose `py-tree-sitter-languages` doesn't require a specific `tree-sitter` version (which it should), so it tries to work with but inevitably fails against versions later than `0.22`.

**Comment by MalikTalha03** [comment]
Thanks. using tree-sitter 0.21.3 solved the issue.

**Comment by walnut211** [comment]
in get_language
    return get_language("java")
           ^^^^^^^^^^^^^^^^^^^^
  File "tree_sitter_languages\\core.pyx", line 14, in tree_sitter_languages.core.get_language
TypeError: __init__() takes exactly 1 argument (2 given)

**Comment by MalikTalha03** [comment]
@walnut211 Please use earlier version of tree-sitter 
pip install tree-sitter==0.21.3
as recommend by @BlastWind 
It worked for me.
